refactor

diff --git a/news b/news
--- a/news
+++ b/news
@@ -2,6 +2,17 @@
 
 set -e -o pipefail
 
+function cleanup(){
+    rm "/tmp/news-${RANDOM_NUMBER}"
+}
+
+function generate_news(){
+    head -n "$REPLY" "/tmp/news-${RANDOM_NUMBER}" \
+      | tail -n 1 | awk -F'\t' '{print "https://explorersweb.com/"$NF}' \
+      | xargs -I{} -- 2>/dev/null curl {} \
+      | grep --only-matching -e '<p>.*</p>' -e '<title>.*</title>' | "$1" -n -3 | pandoc -f html -t plain
+}
+
 function show_help(){
     echo  "USAGE: $0 [category_of_news] [--help]"
     echo  "OPTIONS:"
@@ -11,6 +22,49 @@ function show_help(){
     exit 0
 }
 
+
+function pick_news(){
+    local NUMBER_PATTERN_1="^[0-9]$"
+    local NUMBER_PATTERN_2="^[0-9]{2}$"
+    local QUIT_PATTERN="^[qQ]$"
+    echo
+    read -p "Enter the number for the article you would like to read (or press q to quit) " -n 2 -r
+    echo
+    if [[ $REPLY =~ ${QUIT_PATTERN} ]]; then
+        exit 0
+    fi
+    # Check if it matches pattern , then continue next else just exit out
+    [[ $REPLY =~ ${NUMBER_PATTERN_1} ]] || [[ $REPLY =~ ${NUMBER_PATTERN_2} ]] || { echo "Cannot find number. Pattern not matched..."; exit 1; }
+   
+    # check for ghead or head before attempting to perform this nonsense here
+    if 2>/dev/null command ghead; then
+        local NEWS="$(generate_news 'ghead')"
+    else
+        local NEWS="$(generate_news 'head')"
+    fi
+    
+    local FIRST_LINE="$(echo "$NEWS" | head -n +1)"
+    local EXCEPT_FIRST_LINE=$(echo "$NEWS" | tail -n +2)
+    local SPACES=$(( (TERMINAL_WIDTH - ${#FIRST_LINE}) / 2 ))  
+    local PADDING="$(printf "%${SPACES}s" " ")"
+    printf "%s%s\n%s" "${PADDING}" "${FIRST_LINE}" "${EXCEPT_FIRST_LINE}" | fmt -w ${TERMINAL_WIDTH} | less
+}
+
+function display_news(){
+    declare -i COUNT
+    local COMMAND="$(2>/dev/null curl "${URL_FOR_NEWS}" \
+        | pandoc -t plain | grep -A1 -i -e '<div class="news-card">' \
+        | grep -v -e'<div class="news-card">' | grep -e "${PATTERN}" \
+        | awk -F\" '{print $2}')" 
+    local COUNT=1
+    while read -r LINE; do
+        local TITLE="$(awk -F/ '{print $4}' <(echo "${LINE}"))"
+        echo -e "${COUNT}\t${TITLE}" | tee -a "/tmp/news-${RANDOM_NUMBER}"
+        COUNT=$COUNT+1
+    done < <(echo "${COMMAND}")
+    pick_news
+}
+    
 while getopts ":h" opt; do
     case $opt in
         h)
@@ -65,61 +119,8 @@ WEBSITE="https://explorersweb.com"
 URL_FOR_NEWS="${WEBSITE}/category/${LOWER_CATEGORY}/"
 PATTERN="${URL_FOR_NEWS%*/*/*/}"
 
-function pick_news(){
-    local NUMBER_PATTERN_1="^[0-9]$"
-    local NUMBER_PATTERN_2="^[0-9]{2}$"
-    local QUIT_PATTERN="^[qQ]$"
-    echo
-    read -p "Enter the number for the article you would like to read (or press q to quit) " -n 2 -r
-    echo
-    if [[ $REPLY =~ ${QUIT_PATTERN} ]]; then
-        exit 0
-    fi
-    # Check if it matches pattern , then continue next else just exit out
-    [[ $REPLY =~ ${NUMBER_PATTERN_1} ]] || [[ $REPLY =~ ${NUMBER_PATTERN_2} ]] || { echo "Cannot find number. Pattern not matched..."; exit 1; }
-   
-    # check for ghead or head before attempting to perform this nonsense here
-
-    if 2>/dev/null command ghead; then
-        local NEWS="$(head -n "$REPLY" "/tmp/news-${RANDOM_NUMBER}" \
-                        | tail -n 1 | awk -F'\t' '{print "https://explorersweb.com/"$NF}' \
-                        | xargs -I{} -- 2>/dev/null curl {} \
-                        | grep --only-matching -e '<p>.*</p>' -e '<title>.*</title>' | ghead -n -3 | pandoc -f html -t plain)"
-    else
-        local NEWS="$(head -n "$REPLY" "/tmp/news-${RANDOM_NUMBER}" \
-                        | tail -n 1 | awk -F'\t' '{print "https://explorersweb.com/"$NF}' \
-                        | xargs -I{} -- 2>/dev/null curl {} \
-                        | grep --only-matching -e '<p>.*</p>' -e '<title>.*</title>' | head -n -3 | pandoc -f html -t plain)" 
-    fi
-    
-    local FIRST_LINE="$(echo "$NEWS" | head -n +1)"
-    local EXCEPT_FIRST_LINE=$(echo "$NEWS" | tail -n +2)
-    local SPACES=$(( (TERMINAL_WIDTH - ${#FIRST_LINE}) / 2 ))  
-    local PADDING="$(printf "%${SPACES}s" " ")"
-    printf "%s%s\n%s" "${PADDING}" "${FIRST_LINE}" "${EXCEPT_FIRST_LINE}" | fmt -w ${TERMINAL_WIDTH} | less
-}
-
-function display_news(){
-    declare -i COUNT
-    local COMMAND="$(2>/dev/null curl "${URL_FOR_NEWS}" \
-        | pandoc -t plain | grep -A1 -i -e '<div class="news-card">' \
-        | grep -v -e'<div class="news-card">' | grep -e "${PATTERN}" \
-        | awk -F\" '{print $2}')" 
-    local COUNT=1
-    while read -r LINE; do
-        local TITLE="$(awk -F/ '{print $4}' <(echo "${LINE}"))"
-        echo -e "${COUNT}\t${TITLE}" | tee -a "/tmp/news-${RANDOM_NUMBER}"
-        COUNT=$COUNT+1
-    done < <(echo "${COMMAND}")
-    pick_news
-}
-
 function main(){
     display_news
-}
-
-function cleanup(){
-    rm "/tmp/news-${RANDOM_NUMBER}"
 }
 
 main
